# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AddDual2 <- function(path, subsim_, expected_fitted, Reward_, Scrap_, control_, basis, basis_type) {
    .Call('rlsm_AddDual2', PACKAGE = 'rlsm', path, subsim_, expected_fitted, Reward_, Scrap_, control_, basis, basis_type)
}

AddDual <- function(path, subsim_, fitted_value, Scrap_, basis, basis_type) {
    .Call('rlsm_AddDual', PACKAGE = 'rlsm', path, subsim_, fitted_value, Scrap_, basis, basis_type)
}

PBasis <- function(data, basis, intercept, n_terms, reccur_limit) {
    .Call('rlsm_PBasis', PACKAGE = 'rlsm', data, basis, intercept, n_terms, reccur_limit)
}

LBasis <- function(data, basis, intercept, n_terms, reccur_limit) {
    .Call('rlsm_LBasis', PACKAGE = 'rlsm', data, basis, intercept, n_terms, reccur_limit)
}

Bounds <- function(path, Reward_, Scrap_, control_, mart, path_action) {
    .Call('rlsm_Bounds', PACKAGE = 'rlsm', path, Reward_, Scrap_, control_, mart, path_action)
}

SVDCoeff <- function(xreg, yreg) {
    .Call('rlsm_SVDCoeff', PACKAGE = 'rlsm', xreg, yreg)
}

LSM <- function(path, Reward_, Scrap_, control_, basis, intercept, basis_type) {
    .Call('rlsm_LSM', PACKAGE = 'rlsm', path, Reward_, Scrap_, control_, basis, intercept, basis_type)
}

PathPolicy <- function(path, expected_value, Reward_, control_, basis, intercept, basis_type) {
    .Call('rlsm_PathPolicy', PACKAGE = 'rlsm', path, expected_value, Reward_, control_, basis, intercept, basis_type)
}

TestPolicy <- function(start_position, path, control_, Reward_, Scrap_, path_action) {
    .Call('rlsm_TestPolicy', PACKAGE = 'rlsm', start_position, path, control_, Reward_, Scrap_, path_action)
}

TestPolicy2 <- function(start_position, path, control_, Reward_, Scrap_, path_action) {
    .Call('rlsm_TestPolicy2', PACKAGE = 'rlsm', start_position, path, control_, Reward_, Scrap_, path_action)
}

