# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PBasis <- function(data, basis, intercept, n_terms, reccur_limit) {
    .Call('_rlsm_PBasis', PACKAGE = 'rlsm', data, basis, intercept, n_terms, reccur_limit)
}

LBasis <- function(data, basis, intercept, n_terms, reccur_limit) {
    .Call('_rlsm_LBasis', PACKAGE = 'rlsm', data, basis, intercept, n_terms, reccur_limit)
}

ReccurLimit2 <- function(knots) {
    .Call('_rlsm_ReccurLimit2', PACKAGE = 'rlsm', knots)
}

LSplineBasis <- function(data, knots, n_knots, reccur_limit2) {
    .Call('_rlsm_LSplineBasis', PACKAGE = 'rlsm', data, knots, n_knots, reccur_limit2)
}

Bounds <- function(path, Reward_, Scrap_, control_, mart, path_action) {
    .Call('_rlsm_Bounds', PACKAGE = 'rlsm', path, Reward_, Scrap_, control_, mart, path_action)
}

SVDCoeff <- function(xreg, yreg) {
    .Call('_rlsm_SVDCoeff', PACKAGE = 'rlsm', xreg, yreg)
}

TestPolicy <- function(start_position, path, control_, Reward_, Scrap_, path_action) {
    .Call('_rlsm_TestPolicy', PACKAGE = 'rlsm', start_position, path, control_, Reward_, Scrap_, path_action)
}

FullTestPolicy <- function(start_position, path, control_, Reward_, Scrap_, path_action) {
    .Call('_rlsm_FullTestPolicy', PACKAGE = 'rlsm', start_position, path, control_, Reward_, Scrap_, path_action)
}

