# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PBasis <- function(data, basis, intercept, n_terms) {
    .Call('rlsm_PBasis', PACKAGE = 'rlsm', data, basis, intercept, n_terms)
}

SVDCoeff <- function(xreg, yreg) {
    .Call('rlsm_SVDCoeff', PACKAGE = 'rlsm', xreg, yreg)
}

LSM <- function(path, Reward_, Scrap_, control_, basis, intercept, basis_type) {
    .Call('rlsm_LSM', PACKAGE = 'rlsm', path, Reward_, Scrap_, control_, basis, intercept, basis_type)
}

PathPolicy <- function(path, expected_value, Reward_, control_, basis, intercept, basis_type) {
    .Call('rlsm_PathPolicy', PACKAGE = 'rlsm', path, expected_value, Reward_, control_, basis, intercept, basis_type)
}

BM <- function(start, mu, vol, n_dec, n_path, antithetic) {
    .Call('rlsm_BM', PACKAGE = 'rlsm', start, mu, vol, n_dec, n_path, antithetic)
}

GBM <- function(start, mu, vol, n_dec, n_path, antithetic) {
    .Call('rlsm_GBM', PACKAGE = 'rlsm', start, mu, vol, n_dec, n_path, antithetic)
}

CorrNormal <- function(n, corr) {
    .Call('rlsm_CorrNormal', PACKAGE = 'rlsm', n, corr)
}

CBM <- function(start, mu, vol, corr, n_dec, n_path, antithetic) {
    .Call('rlsm_CBM', PACKAGE = 'rlsm', start, mu, vol, corr, n_dec, n_path, antithetic)
}

CGBM <- function(start, mu, vol, corr, n_dec, n_path, antithetic) {
    .Call('rlsm_CGBM', PACKAGE = 'rlsm', start, mu, vol, corr, n_dec, n_path, antithetic)
}

TestPolicy <- function(start_position, path, control_, Reward_, Scrap_, path_action) {
    .Call('rlsm_TestPolicy', PACKAGE = 'rlsm', start_position, path, control_, Reward_, Scrap_, path_action)
}

TestPolicy2 <- function(start_position, path, control_, Reward_, Scrap_, path_action) {
    .Call('rlsm_TestPolicy2', PACKAGE = 'rlsm', start_position, path, control_, Reward_, Scrap_, path_action)
}

